### ISSUE TITLE
请求数据编码集问题

### ISSUE THREAD

**Issue by LadyChatterleyLover** [Rain120/qq-music-api#1]
你好，为什么我在浏览器测试接口，返回的数据不是中文，而是这种
"dissname": "\ufffd\ufffdѹ\ufffd\ufffdҩ \ufffd\ufffd \ufffd\ufffd\ufffdڰ\ufffdĦ\ufffd\ufffd\ufffd߷\ufffd\ufffd\ufffd"形式的

**Comment by Rain120** [comment]
@LadyChatterleyLover 请问是哪个接口？

**Comment by LadyChatterleyLover** [comment]
暂时只发现分类接口哈

**Comment by Rain120** [comment]
@LadyChatterleyLover 能给路由吗？

**Comment by LadyChatterleyLover** [comment]
http://localhost:3200/getSongListCategories

**Comment by Rain120** [comment]
@LadyChatterleyLover pull一下最新代码，已fix
