### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by 251205668** [Rain120/qq-music-api#11]
服务器部署报错 已经npm install了 运行app.js 不知道为什么
![image](https://user-images.githubusercontent.com/46418596/71186996-2992c480-22b9-11ea-9bb2-69f5bb154246.png)

**Comment by 251205668** [comment]
想请教一下你在服务器部署这个api的地址

**Comment by Rain120** [comment]
@251205668 

![image](https://user-images.githubusercontent.com/20939839/71236126-17f10180-2339-11ea-8316-194ebc816514.png)


建议git pull 最新代码，部署的话，可以直接在服务器上，nohub挂载即可
nohup 挂载
![image](https://user-images.githubusercontent.com/20939839/71236015-c34d8680-2338-11ea-8c9a-3d53f5fd3547.png)

[node 启动](https://rain120.github.io/study-notes/#/notes/nginx/nginx/note?id=%E5%90%AF%E5%8A%A8node)

**Comment by 251205668** [comment]
不知道为什么 在本地就能启动服务 在线上安装依赖后总报这个错误 重复安装了几次都不管用 想问一下你在线上部署的地址
![image](https://user-images.githubusercontent.com/46418596/71261942-8d7cc200-2379-11ea-893a-056b1ab140fa.png)

**Comment by 251205668** [comment]
@Rain120

**Comment by Rain120** [comment]
This issue will close
