### ISSUE TITLE
部署时报错Error: Cannot find module './getHotKey'

### ISSUE THREAD

**Issue by 17665347409** [Rain120/qq-music-api#12]
已经npm install了，依然无法部署
![image](https://user-images.githubusercontent.com/34836531/71536993-cbb54b00-2950-11ea-9720-2c01cbf18f67.png)

**Comment by 17665347409** [comment]
就是换了最新版才出这个问题了，之前的老版本不会

**Comment by Rain120** [comment]
@17665347409 
可以截图看看你的代码，我本地环境没有问题的

**Comment by 17665347409** [comment]
@Rain120 是跟之前那个老哥一样的情况

**Comment by Rain120** [comment]
@17665347409 
![image](https://user-images.githubusercontent.com/20939839/71540127-62016500-2981-11ea-8ad8-f3ec6a301138.png)
请帮我截图看下你那边这个文件的代码，谢谢

**Comment by 251205668** [comment]
同问 搞好了没

**Comment by Rain120** [comment]
能把node版本和这些有关于getHotKey的信息告诉我嘛
![image](https://user-images.githubusercontent.com/20939839/71568013-cd247600-2afe-11ea-93f4-6ea53f1391f5.png)

**Comment by 251205668** [comment]
![image](https://user-images.githubusercontent.com/46418596/71568492-a8320200-2b02-11ea-8c71-b1af75612d0c.png)


报错信息

![Uploading image.png…]()

我尝试过安装这个依赖，但是装不上 前面的老哥也是一样

**Comment by 251205668** [comment]
![image](https://user-images.githubusercontent.com/46418596/71568584-6fdef380-2b03-11ea-97c0-063648e0e0fc.png)

**Comment by 251205668** [comment]
本地能够跑起来 一到线上就报错了

**Comment by Rain120** [comment]
请问你的服务器环境是什么

**Comment by 17665347409** [comment]
@Rain120 CentOS7 64 5.4.0-rc6
node版本应该是最新的 等我回去看看

**Comment by 17665347409** [comment]
![image](https://user-images.githubusercontent.com/34836531/71720287-20c6f480-2e5c-11ea-8d54-ff67fc694617.png)

**Comment by 17665347409** [comment]
![image](https://user-images.githubusercontent.com/34836531/71720347-57047400-2e5c-11ea-870f-609eee1304ba.png)
![image](https://user-images.githubusercontent.com/34836531/71720357-5ff54580-2e5c-11ea-8e3a-86a4604907aa.png)

**Comment by 17665347409** [comment]
![image](https://user-images.githubusercontent.com/34836531/71720376-7ac7ba00-2e5c-11ea-91d1-3c8367e933f5.png)
![image](https://user-images.githubusercontent.com/34836531/71720382-81eec800-2e5c-11ea-976a-d33a80750a3f.png)
![image](https://user-images.githubusercontent.com/34836531/71720393-89ae6c80-2e5c-11ea-8dec-f6f9475c24cc.png)

**Comment by 17665347409** [comment]
@Rain120 
![image](https://user-images.githubusercontent.com/34836531/71720471-dabe6080-2e5c-11ea-910c-928778325610.png)
![image](https://user-images.githubusercontent.com/34836531/71720487-e4e05f00-2e5c-11ea-96d5-2f50551855a0.png)

**Comment by 17665347409** [comment]
@Rain120 代码已经截图了在上面~

**Comment by Rain120** [comment]
@17665347409 
我抽空排查下吧，请稍后，谢谢

**Comment by 17665347409** [comment]
@Rain120 好的谢谢你

**Comment by Rain120** [comment]
@17665347409 @251205668 
非常抱歉，让各位久等了，最近非常忙，没空排查问题
这个 `Bug` 已经解决了，请 `pull` 最新代码即可。
![image](https://user-images.githubusercontent.com/20939839/72704680-6ee63280-3b94-11ea-98e5-20a2192a7751.png)

**Comment by 17665347409** [comment]
@Rain120 依旧不行。。。

已经pull最新版了。。

**Comment by 17665347409** [comment]
> @17665347409 @251205668
> 非常抱歉，让各位久等了，最近非常忙，没空排查问题
> 这个 `Bug` 已经解决了，请 `pull` 最新代码即可。
> **Note**: 如果不行的话，请手动将 `routers/context/getHotkey.js`修改为 `routers/context/getHotKey.js`, 实现不行的话，再使用这个方式
> 
> ![image](https://user-images.githubusercontent.com/20939839/72704680-6ee63280-3b94-11ea-98e5-20a2192a7751.png)
> 
> `Docker Centos` 启动
> 
> ![image](https://user-images.githubusercontent.com/20939839/72704838-cbe1e880-3b94-11ea-95e6-a367ba6c848b.png)

还有这个我没看懂。。。把啥替换成啥

**Comment by Rain120** [comment]
@17665347409 
请再 `git pull` 一下
