### ISSUE TITLE
歌曲的播放地址怎么获取

### ISSUE THREAD

**Issue by MrShepherd** [Rain120/qq-music-api#13]
获取歌曲VKey以后拼接？怎么拼？
看了一下代码，你拼接返回的playlist里的地址有的不能用：000uOIjc0Sp0qm

![微信截图_20200315164246](https://user-images.githubusercontent.com/13277779/76698285-1a66bb80-66dc-11ea-9b0c-64f01f1293ec.png)

还有playlist是空的情况：003aXrl30CqVro
![微信截图_20200315165011](https://user-images.githubusercontent.com/13277779/76698380-22732b00-66dd-11ea-8321-f08c3d263696.png)

**Comment by Rain120** [comment]
@MrShepherd 
现在很多接口都需要登录 or 会员，目前为止，我还没有做这类的接口，所以目前暂时没法获取所有的播放接口

**Comment by LycheeLeaf** [comment]
请问一下作者，怎么样才能调用接口地址，比如这个“接口地址: /downloadQQMusic”?（本人菜鸟，百度了一下，可能关键词不对，没找到答案）求解

**Comment by Rain120** [comment]
@LycheeLeaf 

[文档地址](https://rain120.github.io/qq-music-api/#/?id=%e8%8e%b7%e5%8f%96qq%e9%9f%b3%e4%b9%90%e4%ba%a7%e5%93%81%e7%9a%84%e4%b8%8b%e8%bd%bd%e5%9c%b0%e5%9d%80)

启动项目详见 [README](https://github.com/Rain120/qq-music-api#%E9%A1%B9%E7%9B%AE%E5%90%AF%E5%8A%A8)

更多问题请 提 [issue](https://github.com/Rain120/qq-music-api/issues/new/choose)

**Comment by LycheeLeaf** [comment]
> @LycheeLeaf
> 
> [文档地址](https://rain120.github.io/qq-music-api/#/?id=%e8%8e%b7%e5%8f%96qq%e9%9f%b3%e4%b9%90%e4%ba%a7%e5%93%81%e7%9a%84%e4%b8%8b%e8%bd%bd%e5%9c%b0%e5%9d%80)
> 
> 启动项目详见 [README](https://github.com/Rain120/qq-music-api#%E9%A1%B9%E7%9B%AE%E5%90%AF%E5%8A%A8)
> 
> 更多问题请 提 [issue](https://github.com/Rain120/qq-music-api/issues/new/choose)

好的，谢谢您

**Comment by Melon5kin** [comment]
歌曲的封面地址怎么获取

**Comment by Rain120** [comment]
- 获取歌曲地址 欢迎到 [issue 15](https://github.com/Rain120/qq-music-api/issues/15) 讨论方案，当前 `issue`即将关闭

- @Melon5kin  歌曲的封面地址接口已更新 `getImageUrl`, Plz pull it, [Docs](https://rain120.github.io/qq-music-api/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e6%9b%b2-%e4%b8%93%e8%be%91-%e5%9b%be%e7%89%87)
