### ISSUE TITLE
获取排行榜单详情的接口topId字段无效

### ISSUE THREAD

**Issue by starinsun** [Rain120/qq-music-api#14]
## 举例：
getRanks?topId=26与getRanks?topId=4返回的数据相同，都是默认数据

getRanks?topId=26&limit=15&page=1返回为空

**Comment by Rain120** [comment]
@starinsun 

### Message

First, sorry to not reply to you on time

Second, It has fixed, pull new about it by yourself, more information please go to  [commit](https://github.com/Rain120/qq-music-api/commit/024096fa63144391680f1d6ec376929fee697c37)

### There is the result of the API after fixed

**getRanks?topId=26**

![image](https://user-images.githubusercontent.com/20939839/80556922-c69fff80-8a07-11ea-9b32-5e864e824e3b.png)

**default topId for getRanks**

![image](https://user-images.githubusercontent.com/20939839/80557240-d66c1380-8a08-11ea-8cd0-92a35c9b781e.png)

**Comment by starinsun** [comment]
还是有个问题，这样的话songinfolist一直是空的

**Comment by Rain120** [comment]
@starinsun 

#### Message

It has fixed, pull new about it by yourself, the QQ music API params are changed, more information please go to [commit](https://github.com/Rain120/qq-music-api/commit/f13d2b540d860994600cc2728e4d848df574b2f4)

![image](https://user-images.githubusercontent.com/20939839/80704844-eaeb0180-8b17-11ea-9650-5d77d5b0e16e.png)

![image](https://user-images.githubusercontent.com/20939839/80704814-dd357c00-8b17-11ea-9c5d-e912a5bd2cf0.png)
