### ISSUE TITLE
获取歌单列表参数bug

### ISSUE THREAD

**Issue by hjiachuang** [Rain120/qq-music-api#16]
可选参数

错误的项：
+ _page: 当前页数, 默认为1_
+ _limit: 取出歌单数量, 默认为 20_

实际上：
+ page对应的是获取歌单列表的开始项
+ limit对应的是获取歌单列表的终止项

比如：
page=0，limit=19  表示获取从0到19的歌单列表。
如果要获取下一页的，应传参为：page=20，limit=39

**Comment by hjiachuang** [comment]
再加一个bug提交。
![image](https://user-images.githubusercontent.com/37433108/83648271-6ee94b00-a5e8-11ea-8e57-7f7802aa33eb.png)

**Comment by Rain120** [comment]
@hjiachuang 

**First, thx for your subscribe !!**

**Second, It was fixed, Please got to [commit](https://github.com/Rain120/qq-music-api/commit/d9fb9732f546cb76f208053a8dabd164aad893c5) for review code.**

**Last, pull it.**
