### ISSUE TITLE
获取歌手专辑接口数据错误

### ISSUE THREAD

**Issue by kadaliao** [Rain120/qq-music-api#17]
Bug / Feature:
- 获取歌手转接，预期返回专辑列表，返回的确是歌手热门歌曲列表，并且分页不对。
- 另外没有获取歌手热门歌曲的接口。

复现：
- 访问 /getSingerAlbum?singermid=0025NhlN2yWrP4&page=3 可以复现bug
- 期望增加/getSingerHotsong接口

**Comment by Rain120** [comment]
@kadaliao 

[Pr](https://github.com/Rain120/qq-music-api/pull/18) was merged.
