### ISSUE TITLE
最新的commit彻底挂了 #3330069

### ISSUE THREAD

**Issue by kadaliao** [Rain120/qq-music-api#21]
所有接口都不工作了，不是Not Found，就是Internal Server Error

#20 3330069f0

**Comment by Rain120** [comment]
`Log`

![image](https://user-images.githubusercontent.com/20939839/86530634-d139b200-beec-11ea-952b-a53696670d97.png)

`APIs`

![image](https://user-images.githubusercontent.com/20939839/86530593-9a639c00-beec-11ea-85bb-4da600feb155.png)
 
我本地是OK

**Comment by kadaliao** [comment]
奇怪了，可能昨天我电脑问题。
