### ISSUE TITLE
获取轮播图的API怎么调用

### ISSUE THREAD

**Issue by chuxincx** [Rain120/qq-music-api#23]
我在API结构图看到是有的，但是在文档中并没有找到轮播图API

**Comment by Rain120** [comment]
@chuxincx 

### Link to [获取数字专辑](https://rain120.github.io/qq-music-api/#/?id=%e8%8e%b7%e5%8f%96%e6%95%b0%e5%ad%97%e4%b8%93%e8%be%91)

### 目前只有这个 `banner`

![image](https://user-images.githubusercontent.com/20939839/87008839-ea957380-c1f6-11ea-9253-862825133466.png)

**Comment by chuxincx** [comment]
好的，谢谢了
