### ISSUE TITLE
不管怎么修改参数，返回的都是搜索歌曲，不能搜索其他类型

### ISSUE THREAD

**Issue by Eddy0Hoang** [Rain120/qq-music-api#28]
文档上面写的是修改catZhida参数，但是修改了没用，我又去看了QQ音乐的链接，发现各种搜索的catZhida值都是一样的，变的是remoteplace参数，但是我用你的项目修改了这个参数返回结果还是一样的songs，希望作者能修复一下这个问题

**Comment by Rain120** [comment]
@Eddy0Hoang 
你能描述下哪个接口吗？最好截个图

**Comment by Eddy0Hoang** [comment]
/getSearchByKey?key=onerepublic&catZhida=0  ,这个接口，修改catZhida参数对搜索结果没有影响

**Comment by Rain120** [comment]
fixed and pull it
