### ISSUE TITLE
docker支持

### ISSUE THREAD

**Issue by Tao173** [Rain120/qq-music-api#29]
请问可以再docker下配置么？因为网易云那个我是在docker下运行的，机器本身cpu比较特殊。。。。斐讯N1，

**Comment by Rain120** [comment]
@Tao173 

试试这个镜像能不能使用

```sh
docker pull qq-music-api
```

文档: [Docker](https://github.com/Rain120/qq-music-api/blob/master/README.md#-docker)

**Comment by Tao173** [comment]
OK，我试试看，谢谢老哥👍

**Comment by Rain120** [comment]
@Tao173

已更新，再试试

**Comment by Tao173** [comment]
好的，我想试试看😬
@Rain120

**Comment by Rain120** [comment]
@Tao173 
如果没有问题，我就关闭了
