### ISSUE TITLE
下载下来安装包跑了一遍提示404啊

### ISSUE THREAD

**Issue by EmilyHOC** [Rain120/qq-music-api#3]
### 环境

系统:

nodejs 版本(koa2要求版本是7.6.0+):

### 期待效果

> 重现步骤尽量详细,不能含糊不清

> 如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Rain120** [comment]
@EmilyHOC 如何复现？或者说你如何操作的？
