### ISSUE TITLE
无法下载歌曲

### ISSUE THREAD

**Issue by iwxyi** [Rain120/qq-music-api#31]
搜索歌曲后，请问怎么下载歌曲呢？`response.data.song.list` 中歌曲的 `"url": "http://stream10.qqmusic.qq.com/xxx.wma` 下不动

**Comment by Rain120** [comment]
@iwxyi

**Comment by iwxyi** [comment]
那怎么播放歌曲呀？

**Comment by Rain120** [comment]
@iwxyi 周末有时间的话整下，请Nice等待下，现在是要自己组合链接

**Comment by Rain120** [comment]
@iwxyi @zxywater

[获取歌曲播放链接](https://rain120.github.io/qq-music-api/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e6%9b%b2%e6%92%ad%e6%94%be%e9%93%be%e6%8e%a5)

**Comment by iwxyi** [comment]
> @iwxyi @zxywater
> 
> ### 获取歌曲播放链接
> [获取歌曲播放链接](https://rain120.github.io/qq-music-api/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e6%9b%b2%e6%92%ad%e6%94%be%e9%93%be%e6%8e%a5)
> 
> ### 获取歌曲下载地址链接
> **下载地址就是播放地址**
> 
> ![image](https://user-images.githubusercontent.com/20939839/105622845-c24a2b00-5e4f-11eb-88ee-634bad33a56e.png)
> 
> 相关可以查看 [PR](https://github.com/Rain120/qq-music-api/pull/34)

谢谢大佬！
