### ISSUE TITLE
有播放歌曲的api么?

### ISSUE THREAD

**Issue by zhaokuohaha** [Rain120/qq-music-api#4]
> 不好意思哈， 因为不是很好根据模板描述， 就不按照模板来了

我想问下现在有播放歌曲的api了么？ 我看了下api结构图是有的， 但是没有找到。 搜索接口返回的url 类似 ` "url": "http://stream10.qqmusic.qq.com/718478.wma",` 这个， 直接请求的话是404

**Comment by Rain120** [comment]
@zhaokuohaha 详见 [获取歌曲VKey](https://rain120.github.io/qq-music-api/#/?id=%E8%8E%B7%E5%8F%96%E6%AD%8C%E6%9B%B2vkey)
