### ISSUE TITLE
文档的网址挂掉了，可以处理一下吗

### ISSUE THREAD

**Issue by callmehui** [Rain120/qq-music-api#45]
### 环境

系统:

nodejs 版本(koa2要求版本是7.6.0+):

### 期待效果

> 重现步骤尽量详细,不能含糊不清

> 如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Rain120** [comment]
https://rain120.github.io/qq-music-api/#/
