### ISSUE TITLE
api接口返回内容为空

### ISSUE THREAD

**Issue by djkcyl** [Rain120/qq-music-api#59]
http://localhost:3200/getCookie
```json
Not Found
```
http://localhost:3200/getSearchByKey?key=%E5%91%A8%E6%9D%B0%E4%BC%A6
```json
{"response":{"code":0,"data":{"keyword":"周杰伦","priority":0,"qc":[],"semantic":{"curnum":0,"curpage":0,"list":[],"totalnum":0},"song":{"curnum":0,"curpage":1,"list":[],"totalnum":0},"tab":0,"taglist":[],"totaltime":0,"zhida":null},"message":"","notice":"","subcode":0,"time":1642434810,"tips":""}}
```

**Comment by zhaoyongping** [comment]
getSearchByKey 搜索接口失效了

**Comment by Rain120** [comment]
可能因为QQ获取cookie的策略有所变更，目前比较繁忙，请问下你有时间协助定位或者修复一下吗？辛苦🎉

**Comment by djkcyl** [comment]
> 可能因为QQ获取cookie的策略有所变更，目前比较繁忙，请问下你有时间协助定位或者修复一下吗？辛苦🎉

时间是有，不过我比较菜，不会nodejs（

**Comment by Rain120** [comment]
#68 https://github.com/Rain120/qq-music-api/issues/68
