### ISSUE TITLE
没用户登陆的接口。。。

### ISSUE THREAD

**Issue by ZoeLeee** [Rain120/qq-music-api#6]
### 环境

系统:

nodejs 版本(koa2要求版本是7.6.0+):

### 期待效果

> 重现步骤尽量详细,不能含糊不清

> 如果不是提建议,提 issues 如果不照着模版来将不会优先处理或直接关闭

**Comment by Rain120** [comment]
登录接口一直没时间看，就没弄

**Comment by Rain120** [comment]
@ZoeLeee 登录接口一直没时间看，就没弄

**Comment by Rain120** [comment]
@ZoeLeee 需求已经考虑过了，挑时间尝试一下，或者欢迎大佬PR
