### ISSUE TITLE
搜索api返回结果没有内容

### ISSUE THREAD

**Issue by SUN7700** [Rain120/qq-music-api#68]
![image](https://user-images.githubusercontent.com/68912523/160579512-9e6c1e04-81fb-47ce-9f78-9857ff2ac99b.png)

**Comment by dipelta** [comment]
发现了同样的问题，需要修改module/apis/search/getSearchByKey.js中第9行，去掉new_json的请求参数就行了

**Comment by Rain120** [comment]
@dipelta 感谢同学提醒

**Comment by SUN7700** [comment]
好像还是不行啊

**Comment by dipelta** [comment]
@SUN7700 刚刚从master分支上又试了下，没有问题

**Comment by Littlekid-cup** [comment]
Internal Server Error 是什么鬼

**Comment by FengXiaoBing-ui** [comment]
Internal Server Error 这个项目搜索接口已经不行了吗
