### ISSUE TITLE
很多歌曲获取不了播放链接的，比如北京北京

### ISSUE THREAD

**Issue by kangear** [Rain120/qq-music-api#7]
/getMusicVKey?songmid=001fkWNw2eaEYT

**Comment by Rain120** [comment]
@kangear 
这个字段为空，所以取不到，只是部分接口取不到，有一些测试没问题，需要挑时间，慢慢看
**Error**
![image](https://user-images.githubusercontent.com/20939839/65386891-7971f600-dd73-11e9-8188-4d90631b1134.png)
**Normal**
```http
/getMusicVKey?songmid=003JXflt0ohuO9
```
![image](https://user-images.githubusercontent.com/20939839/65386909-cce44400-dd73-11e9-9aef-b94cae09ba21.png)

**Comment by pibeyag206** [comment]
Same issue. :(

![localhost_3200_getMusicVKey_songmid=003kLCl33HT2vB (3)](https://user-images.githubusercontent.com/57705786/68749749-cb1a5c80-060f-11ea-9b96-402bfeb6a5d5.png)

**Comment by Rain120** [comment]
@pibeyag206 有空看看QQ音乐更新了那些东西，请耐心等候

**Comment by jieruian** [comment]
> @pibeyag206 有空看看QQ音乐更新了那些东西，请耐心等候

是这样的，我对比了，拿不到地址的歌曲是要买会员的歌曲，就是冲88块钱才能听的歌曲

**Comment by Rain120** [comment]
@jieruian 是的，如果没问题的话，我就关闭了，谢谢关注
