### ISSUE TITLE
请问是否有搜索歌曲详细信息的api

### ISSUE THREAD

**Issue by Frozenmad** [Rain120/qq-music-api#8]
很不错的项目，谢谢作者的贡献！

我的需求是，给定一个歌曲的mid，我需要知道该歌曲的“名称”，“歌手”，“专辑“，”封面“等一系列信息（也就是搜索歌曲时返回的那些信息）。具体来说，功能类似于[这个网易云api](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e6%9b%b2%e8%af%a6%e6%83%85)。我好像在文档里没找到相关的接口，希望能作者补充这个接口，谢谢！

**Comment by Rain120** [comment]
@Frozenmad 
![image](https://user-images.githubusercontent.com/20939839/70533403-fb640500-1b93-11ea-9904-f69e93fd2c0b.png)

**Comment by Frozenmad** [comment]
@Rain120 感谢回复！

不过这些还不能解决我的需求，我现在只有某些歌曲的id（歌曲名字也未知），现在想获得这个id对应的歌曲的所有信息。目前的解决办法是换了[另外一个项目的接口](https://jsososo.github.io/QQMusicApi/#/?id=%e6%ad%8c%e6%9b%b2%e4%bf%a1%e6%81%af)。

希望此项目也能补充~

**Comment by Rain120** [comment]
@Frozenmad 有时间的话，会补上的，请耐心等候

**Comment by Rain120** [comment]
@Frozenmad  The feature has done. if you want it, pull new plz.
![image](https://user-images.githubusercontent.com/20939839/70863390-bf111a00-1f82-11ea-9d18-8f897ff70119.png)

**Comment by Frozenmad** [comment]
@Rain120 

Thank you for the great update!

Just small advice: I've tested the new API, it works perfectly. However, it seems not to support querying batch data (multiple mid querying at once). 

Does the raw QQ music API support batchable queries? If so, can this API be converted to a batchable one? Many thanks!

**Comment by Rain120** [comment]
@Frozenmad plz new an issue for feature, thx
