### ISSUE TITLE
Require multi music info from batch mid

### ISSUE THREAD

**Issue by Frozenmad** [Rain120/qq-music-api#9]
**Is your feature request related to a problem? Please describe.**
The music info API request from issue #8 is handled perfectly! However, the new API does not support **querying multi music info**. Querying multi music info at once is useful _when you are trying to load a bunch of music (say, a new music playlist)_. Querying their info one by one is time-inefficient and will easily result in the block of raw QQ API (I think :P).

**Describe the solution you'd like**
I want a new (or modification of the origin) API, which I can get a list of music info back. One can refer to this [netease API](https://binaryify.github.io/NeteaseCloudMusicApi/#/?id=%e8%8e%b7%e5%8f%96%e6%ad%8c%e6%9b%b2%e8%af%a6%e6%83%85) for the detailed design :).

Thanks for the great work again!

**Comment by Rain120** [comment]
@Frozenmad batch get song lists, music info need more time, plz hold on, thx
